#!/usr/bin/env python

from process.globals import load_config

from process.lock import begin, end
from fundraising_ab_tests.spec_gdoc import update_gdoc_spec

from process.globals import get_config

begin()

load_config("analysis")
update_gdoc_spec(doc=get_config().spec_db.spec.url)

end()
