#!/usr/bin/env python

from process.logging import Logger as log
from process.globals import load_config
load_config("analysis")

from process.lock import begin, end
from fundraising_ab_tests.spec_gdoc import update_gdoc_spec

from process.globals import get_config

begin()

update_gdoc_spec(doc=get_config().spec_db.spec.url)

end()
