#!/usr/bin/env python

from process.globals import load_config
load_config("config.py")

from process.lock import begin, end
from fundraising_ab_tests.spec_gdoc import update_gdoc_spec

from process.globals import config

begin()

update_gdoc_spec(doc=config.test_spec_url)

end()
