#!/usr/bin/env python

from process.logging import Logger as log

from process.globals import load_config
load_config("globalcollect-audit")

import process.lock as lock
import sftp.client

if __name__ == '__main__':
    log.info("Begin GlobalCollect nightly audit download")
    lock.begin()

    sftp.client.Crawler.pull()

    lock.end()
    log.info("End GlobalCollect nightly audit download")
