#!/bin/bash
# usage: download_nightly_redux <incomingdir> <completeddir> <connectstring> <privkeypath> <outputdir>
for file in $( \
  diff \
    <(find ${1} ${2} -type f -printf "%f\n"|sort|uniq) \
    <(ssh -q -i ${4} ${3} ls out|sort) \
  |sed -n 's/^> \(.*\)/\1/p'
); do
  scp -q -i ${4}  ${3}:/out/${file} ${5}
done
