#!/bin/bash
# usage: download_nightly_redux <incomingdir> <completeddir> <connectstring> <privkeypath> <remotedir>
for file in $( \
  diff \
    <(find ${1} ${2} -type f -printf "%f\n"|sort|uniq) \
    <(ssh -q -i ${4} ${3} ls ${5}|sort) \
  |sed -n 's/^> \(.*\)/\1/p'
); do
  scp -i ${4} ${3}:/${5}/${file} ${1}
done
