#!/usr/bin/env python

import logging

from process.globals import load_config

import process.lock as lock
import sftp.client

log = logging.getLogger(__name__)


if __name__ == '__main__':
    load_config("astropay-audit")
    log.info("Begin Astropay nightly audit download")
    lock.begin()

    sftp.client.Crawler.pull()

    lock.end()
    log.info("End Astropay nightly audit download")
