#!/usr/bin/env python

from process.log import Logger as log

from process.globals import load_config

import process.lock as lock
import sftp.client

if __name__ == '__main__':
    load_config("paypal-audit")
    log.info("Begin PayPal nightly audit download")
    lock.begin()

    sftp.client.Crawler.pull()

    lock.end()
    log.info("End PayPal nightly audit download")
