<?php

//read in xml
$contents = file_get_contents( 'country_names_and_code_elements_xml.htm' );
$doc = new SimpleXMLElement( $contents );

//populate the data array
$data = array( );

foreach ( $doc->xpath( '//ISO_3166-1_Entry/ISO_3166-1_Alpha-2_Code_element' ) as $elem ) {
	$data[] = ( string ) $elem;
}

//write the data to a file
//
//Yes, I am aware I could have simply used var_export.
//...the spacing was ugly.
$output = "<?php\n";
$output .= "/*\n\tList of valid iso 3166 country codes, regenerated on " . time() . " \n";
$output .= "\tCode generated by a happy script at \n";
$output .= "\thttps://gerrit.wikimedia.org/r/#/admin/projects/wikimedia/fundraising/tools,branches\n";
$output .= "*/\n";


$output .= "\n\$iso_3166_codes = array(\n\t";
$limit = 14;
$i = 0;
foreach ( $data as $value ) {
	if ( $i === $limit ) {
		$output .= "\n\t";
		$i = 0;
	}
	$output .= "'$value',";
	++$i;
}
$output .= "\n);\n";

//$output = var_export( $data, true );

file_put_contents( 'iso3166codes.php', $output );
?>
