#!/usr/bin/env python3

import logging

from process.globals import load_config

import process.lock as lock
import sftp.client

log = logging.getLogger(__name__)


if __name__ == '__main__':
    load_config("dlocal-audit")
    log.info("Begin Dlocal nightly audit download")
    lock.begin()

    sftp.client.Crawler.pull()

    lock.end()
    log.info("End Dlocal nightly audit download")
