#!/usr/bin/env python

import os, os.path
import re
import shutil
from process.logging import Logger as log
from process.globals import load_config
load_config("worldpay-audit")
from process.globals import config
import process.lock as lock

import TransactionReconciliationFile

handlers = [
    TransactionReconciliationFile.TransactionReconciliationFile,
]

def parse(path):
    for handler in handlers:
        if handler.is_mine(path):
            log.info("Parsing file {path} using {type} handler".format(path=path, type=handler))
            handler.handle(path)
            return

    log.info("Skipping file with no handlers: {path}".format(path=path))

def archive(path):
    filename = os.path.basename(path)
    dest_path = os.path.join(config.archive_path, filename)

    log.info("Archiving {orig} to {new}".format(orig=path, new=dest_path))
    shutil.move(path, dest_path)

if __name__ == '__main__':
    lock.begin()

    for filename in os.listdir(config.incoming_path):
        path = os.path.join(config.incoming_path, filename)
        if os.path.isfile(path):
            parse(path)
            #archive(path)

    lock.end()
